name: Branch Deployments

on:
  pull_request:
    branches:
      - main  # Adjust this to your main branch

jobs:
  Code-Quality-and-Static-Analysis:
    name: Code Quality and Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run Pysa Action
        uses: facebook/pysa-action@15c7aea01cff64049bafe04fac871bd2cb50df56
        with:
          repo-directory: './tla_example'
          requirements-path: 'requirements.txt'
          infer-types: true
          include-default-sapp-filters: true

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs:
      - Code-Quality-and-Static-Analysis
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: valentinofantini/scaffolding
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    
  Deploy-to-Development:
    name: Deploy to development environment
    runs-on: ubuntu-latest
    needs:
      - Code-Quality-and-Static-Analysis
      - push_to_registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Deploy to development
        run: echo "Deploying to development environment..."

